### ISSUE TITLE
Indicate which license this extension is under

### ISSUE THREAD

**Issue by degoeym** [deriegle/vscode-test-file-finder#1]
Running `npm install` presents you with a warning about not having a license field in `package.json`:

![image](https://user-images.githubusercontent.com/4965901/46621151-ba3a1600-caf4-11e8-9c8f-bd9d60b7f8cb.png)

Per the npm docs related to package.json, it's recommended to have a [license property](https://docs.npmjs.com/files/package.json#license) so others know how they're permitted to use the code.

**Comment by deriegle** [comment]
Thank you!!
I resolved this issue in PR #3 which adds the MIT license to the project.
