### ISSUE TITLE
Feature request: typescript

### ISSUE THREAD

**Issue by lonix1** [deriegle/vscode-test-file-finder#11]
It doesn't find my typescript tests.

Please add native support for typescript, so we don't need to pollute the `package.json` with non-project stuff?

So: `"testFinder.typescriptGlob": ".test.ts"`.

**Comment by deriegle** [comment]
Typescript has been added in https://github.com/deriegle/vscode-test-file-finder/commit/95a984b52f09d859bed08c01bbbc7134c44461a7.

I will post in here again and close this when I've upgraded the package on the vscode marketplace. Sorry this took so long.

Also, You don't need to update your own `package.json` file. The [README](https://github.com/deriegle/vscode-test-file-finder#adding-support-for-new-test-files) is referring to how you can configure this project to accept different test files

**Comment by deriegle** [comment]
Version `0.1.1` has been published with typescript & typescript react (TSX) support. Make sure to upgrade to at least this version and if you need a custom test file glob, make sure to define that in your custom settings with `testFinder.typescriptGlob` or `testFinder.typescriptreactGlob`. Let me know if you need any additional help.
